{
 "title": "Promtheus Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "rate(http_requests_total[1m])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "increase(http_requests_total[1m])",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}